server:
  port: 8001
  servlet:
    encoding:
      force: true
      charset: UTF-8
  tomcat:
    threads:
      max: 3000
      min-spare: 300
    accept-count: 300
    connection-timeout: 60000
    max-keep-alive-requests: 300
    max-connections: 10000
    max-http-form-post-size: 10

  max-http-header-size: 128000

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/saber66.p12
    key-store-password: saber@123
    key-alias: saber66
    enabled: true


springfox:
  documentation:
    swagger:
      v2:
        path: '/services/person-docs/v2/api-docs'

cxf:
  path: /soapServices
  endpoint: /personSoap
  host: localhost
  soapGatewayPort: 8000


spring:
  application:
    name: person-service
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:person
  #    username: sa
  #    password: sa
  #    hikari:
  #      maximum-pool-size: 100
  #      minimum-idle: 35
  #      max-lifetime: 10000
  #      idle-timeout: 8000
  #      connection-timeout: 8000
  #      initialization-fail-timeout: 8000
  c3p0:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    minPoolSize: 40
    maxPoolSize: 100
    initialPoolSize: 50
    acquireIncrement: 10
    acquireRetryDelay: 600
    checkTimeout: 10000
    maxConnectionAge: 30
    maxIdleTimeout: 30
    maxStatementPerConnection: 100
    idleConnectionTestPeriod: 180
    testConnectionOnCheckout: false
    testConnectionOnCheckin: true
    numHelperThreads: 100
    preferredTestQuery: 'SELECT 1'
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true

camel:
  springboot:
    route-controller-thread-pool-size: 6000
    jmx-management-statistics-level: extended
    consumer-template-cache-size: 6000
    producer-template-cache-size: 6000
    backlog-tracing: true
  dataformat:
    json-jackson:
      pretty-print: true
      auto-discover-object-mapper: true






hawtio:
  authenticationEnabled: false
management:
  metrics:
  distribution:
    percentiles-histogram:
      "[http.server.requests]": true
    sla:
      "[http.server.requests]": 10ms, 100ms
    percentiles:
      "[http.server.requests]": 0.5, 0.75, 0.95, 0.98, 0.99, 0.999, 1.0
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      base-path: /actuators/person
      exposure:
        include: '*'

